# Generated by Django 5.1.6 on 2025-03-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='massage',
            new_name='message',
        ),
    ]
